# Generated by Django 3.1.6 on 2021-03-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_history_input_manufacturer_personal_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20)),
                ('product_quantity', models.PositiveIntegerField()),
                ('date_output', models.DateField()),
            ],
        ),
    ]
