# Generated by Django 3.1.6 on 2021-03-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_history_input_manufacturer_personal_product_product_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='preorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20)),
                ('balance', models.IntegerField()),
                ('employee', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code1_4', models.CharField(max_length=4)),
                ('code5_6', models.CharField(max_length=2)),
                ('code7_9', models.CharField(max_length=3)),
                ('code', models.TextField(blank=True, max_length=50)),
                ('value', models.IntegerField()),
                ('valueremain', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_balance',
            field=models.IntegerField(default=0),
        ),
    ]
