# Generated by Django 3.1.6 on 2021-04-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20210403_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
