# Generated by Django 3.1.6 on 2021-03-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20210310_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('employee', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('store_id', models.CharField(max_length=20)),
                ('store_t', models.TextField()),
                ('store_a', models.TextField()),
                ('store_city', models.TextField()),
                ('store_post', models.CharField(max_length=20)),
                ('store_email', models.EmailField(max_length=254)),
                ('store_phone', models.CharField(max_length=20)),
                ('store_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='store_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=20)),
                ('product_code', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
