# Generated by Django 3.1.6 on 2021-03-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_basket_store_store_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('shop_name', models.CharField(max_length=50)),
                ('employee', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('date_sended', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
