# Generated by Django 3.1.6 on 2021-03-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_product_shelf'),
    ]

    operations = [
        migrations.CreateModel(
            name='check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20)),
                ('shelf_id', models.TextField(blank=True, max_length=50)),
                ('qty', models.IntegerField()),
                ('employee', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
