# Generated by Django 3.1.6 on 2021-03-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_sended',
            field=models.DateField(null=True),
        ),
    ]
