# Generated by Django 3.1.6 on 2021-04-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_auto_20210404_0642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='history_list',
            new_name='history_lost',
        ),
    ]
