# Generated by Django 3.1.6 on 2021-04-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_auto_20210404_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_product_shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('shelf_id', models.TextField(blank=True, max_length=50)),
                ('total', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
