# Generated by Django 3.1.6 on 2021-03-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_auto_20210312_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_sended',
            field=models.DateField(blank=True, default=None),
        ),
    ]
