# Generated by Django 3.1.6 on 2021-04-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_history_product_shelf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelf',
            old_name='code7_9',
            new_name='value_status',
        ),
    ]
