# Generated by Django 3.1.6 on 2021-03-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_auto_20210312_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='saled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20)),
                ('shop_name', models.CharField(max_length=50)),
                ('employee', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
