# Generated by Django 3.1.6 on 2021-04-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_auto_20210409_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('from_shelf', models.TextField(blank=True, max_length=50)),
                ('to_shelf', models.TextField(blank=True, max_length=50)),
                ('employee', models.CharField(max_length=70)),
            ],
        ),
    ]
