# Generated by Django 3.1.6 on 2021-04-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0009_history_move'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20)),
                ('shelf_id', models.TextField(blank=True, max_length=50)),
                ('qty', models.IntegerField()),
                ('group', models.CharField(max_length=20)),
            ],
        ),
    ]
