# Generated by Django 3.1.6 on 2021-04-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0011_auto_20210410_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Month_qty_ago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(default='', max_length=20)),
                ('Jan', models.IntegerField(default=0)),
                ('Feb', models.IntegerField(default=0)),
                ('Mar', models.IntegerField(default=0)),
                ('Apr', models.IntegerField(default=0)),
                ('May', models.IntegerField(default=0)),
                ('Jun', models.IntegerField(default=0)),
                ('Jul', models.IntegerField(default=0)),
                ('Aug', models.IntegerField(default=0)),
                ('Sep', models.IntegerField(default=0)),
                ('Oct', models.IntegerField(default=0)),
                ('Nov', models.IntegerField(default=0)),
                ('Dec', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Month_qty_now',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(default='', max_length=20)),
                ('Jan', models.IntegerField(default=0)),
                ('Feb', models.IntegerField(default=0)),
                ('Mar', models.IntegerField(default=0)),
                ('Apr', models.IntegerField(default=0)),
                ('May', models.IntegerField(default=0)),
                ('Jun', models.IntegerField(default=0)),
                ('Jul', models.IntegerField(default=0)),
                ('Aug', models.IntegerField(default=0)),
                ('Sep', models.IntegerField(default=0)),
                ('Oct', models.IntegerField(default=0)),
                ('Nov', models.IntegerField(default=0)),
                ('Dec', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.TextField(),
        ),
    ]
